/**
 * constants module stores the shared constants for the achievements extension
 *
 * @author BoxBoxJason
 */

import path from 'path';

/**
 * Constants for the achievements extension
 *
 * @namespace constants
 */
export namespace constants {
  //////////////////////// CATEGORIES ////////////////////////
  export const enum category {
    FILES= 'files',
    GIT= 'git',
    PRODUCTIVITY= 'productivity',
    VSCODE= 'vscode'
  };

  //////////////////////// CRITERIAS ////////////////////////
  export enum criteria {
    LINES_OF_CODE= 'linesOfCodeCount',
    LINES_OF_CODE_LANGUAGE= 'linesOfCodeCount_%s',
    LINES_OF_COMMENTS= 'linesOfCommentsCount',
    NUMBER_OF_PASTES= 'pastesCount',
    ERRORS_FIXED= 'errorsFixedCount',
    DIRECTORY_CREATED= 'directoryCreatedCount',
    RESOURCE_DELETED= 'resourceDeletedCount',
    FILES_RENAMED= 'filesRenamedCount',
    FILES_CREATED= 'filesCreatedCount',
    FILES_CREATED_LANGUAGE= 'filesCreatedCount_%s',
    COMMITS= 'commitsCount',
    BRANCHES_CREATED= 'branchesCreatedCount',
    MERGES_AND_REBASES= 'mergesAndRebasesCount',
    AMENDS= 'amendsCount',
    FORCED_PUSHES= 'forcedPushesCount',
    PUSHES= 'pushesCount',
    NUMBER_OF_SIMULTANEOUS_TABS= 'simultaneousTabsCount',
    DAILY_TIME_SPENT= 'dailyTimeSpentCount',
    TWO_WEEKS_TIME_SPENT= 'twoWeeksTimeSpentCount',
    MONTHLY_TIME_SPENT= 'monthlyTimeSpentCount',
    YEARLY_TIME_SPENT= 'yearlyTimeSpentCount',
    TOTAL_TIME_SPENT= 'totalTimeSpentCount',
    EXTENSIONS_INSTALLED= 'extensionsInstalledCount',
    EXTENSIONS_OUTDATED= 'extensionsOutdatedCount',
    THEMES_INSTALLED= 'themesInstalledCount',
    DEBUGGER_SESSIONS= 'debuggerSessionsCount',
    TERMINAL_COMMANDS= 'terminalCommandsCount',
    CODE_SNIPPETS= 'codeSnippetsCount',
  };

  //////////////////////// LABELS ////////////////////////
  export const labels = {
    LINES_OF_CODE: 'lines of code',
    LINES_OF_COMMENTS: 'lines of comments',
    NUMBER_OF_PASTES: 'number of pastes',
    ERRORS_FIXED: 'errors fixed',
    RESOURCE_CREATED: 'resource created',
    RESOURCE_DELETED: 'resource deleted',
    COMMITS: 'commits',
    BRANCHES_CREATED: 'branches created',
    MERGES_AND_REBASES: 'merges and rebases',
    AMENDS: 'amends',
    FORCED_PUSHES: 'forced pushes',
    PUSHES: 'pushes',
    NUMBER_OF_SIMULTANEOUS_TABS: 'number of simultaneous tabs',
    TIME_SPENT: 'time spent',
    EXTENSIONS_INSTALLED: 'extensions installed',
    EXTENSIONS_OUTDATED: 'extensions outdated',
    THEMES_INSTALLED: 'themes installed',
    DEBUGGER_SESSIONS: 'debugger sessions',
    TERMINAL_COMMANDS: 'terminal commands',
    CODE_SNIPPETS: 'code snippets',
    LANGUAGES: {
      JAVA: 'java',
      PYTHON: 'python',
      JAVASCRIPT: 'javascript',
      TYPESCRIPT: 'typescript',
      ADA: 'ada',
      C: 'c',
      CPP: 'c++',
      CSHARP: 'c#',
      RUBY: 'ruby',
      PHP: 'php',
      SWIFT: 'swift',
      KOTLIN: 'kotlin',
      GO: 'go',
      RUST: 'rust',
      HTML: 'html',
      CSS: 'css',
      SCSS: 'scss',
      LESS: 'less',
      SQL: 'sql',
      SHELL: 'shell',
      BASH: 'bash',
      POWERSHELL: 'powershell',
      COBOL: 'cobol',
      FORTRAN: 'fortran',
      PASCAL: 'pascal',
      PERL: 'perl',
      LUA: 'lua',
      MATLAB: 'matlab',
      OBJECTIVEC: 'objective-c',
      SCALA: 'scala',
      HASKELL: 'haskell',
      R: 'r',
    } as const,
    LANGUAGES_EXTENSIONS: {
      '.java': 'java',
      '.py': 'python',
      '.js': 'javascript',
      '.jsx': 'javascript',
      '.ts': 'typescript',
      '.tsx': 'typescript',
      '.ada': 'ada',
      '.c': 'c',
      '.h': 'c',
      '.cpp': 'c++',
      '.hpp': 'c++',
      '.cs': 'c#',
      '.rb': 'ruby',
      '.php': 'php',
      '.swift': 'swift',
      '.kt': 'kotlin',
      '.kts': 'kotlin',
      '.go': 'go',
      '.rs': 'rust',
      '.html': 'html',
      '.htm': 'html',
      '.css': 'css',
      '.scss': 'scss',
      '.sass': 'scss',
      '.less': 'less',
      '.sql': 'sql',
      '.sh': 'shell',
      '.bash': 'bash',
      '.zsh': 'bash',
      '.ps1': 'powershell',
      '.psm1': 'powershell',
      '.cbl': 'cobol',
      '.cob': 'cobol',
      '.f': 'fortran',
      '.f90': 'fortran',
      '.f95': 'fortran',
      '.pas': 'pascal',
      '.pp': 'pascal',
      '.pl': 'perl',
      '.pm': 'perl',
      '.lua': 'lua',
      '.m': 'objective-c',
      '.mat': 'matlab',
      '.scala': 'scala',
      '.sc': 'scala',
      '.hs': 'haskell',
      '.lhs': 'haskell',
      '.r': 'r',
      '.R': 'r',
    } as { [key: string]: string },
  } as const;

  export const build = {
    EXTENSION_ENTRYPOINTS: [path.join('src','extension.ts')],
    EXTENSION_OUT_FILE: path.join('dist','extension.js'),
    WEBVIEW_ENTRYPOINTS: [path.join('src','views','index.tsx')],
    WEBVIEW_OUT_FILE: path.join('dist','webview.js'),
  } as const;

}
